config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root 'users#index'
  resources :users, only: :new

  resources :persons
  get 'people', to: 'persons#people'
end

app/views/shared/_form.html.haml
.new_people__create
  %l1 リスト登録
  = form_for @person, url: persons_path, html: {class: "people_new"} do |f|
    = render 'layouts/error_messages', model: f.object
    = f.label :name, "本名　又は　ニックネーム"
    = f.text_field :name
    %br
    = f.label :gender, "性別"
    = f.select :gender, Person.genders.keys, {prompt: '---'}
    = f.label :age, "年齢"
    = f.select :age, Person.ages.keys, {prompt: '---'}
    = f.label :body, "体型"
    = f.select :body, Person.bodys.keys, {prompt: '---'}
    %br/
    = f.label :height, "身長"
    = f.select :height, Person.heights.keys, {prompt: '---'}
    = f.label :hair, "髪型"
    = f.select :hair, Person.hairs.keys, {prompt: '---'}
    %br
    #chara-box
      = f.fields_for :characters do |c|
        .js-file_group{"data-index" => "#{c.index}"}
          = c.label :chara, "特徴", class: 'js-file'
          = c.text_field :chara, class: 'js-file'
          %input{name: "button", type: "button", value: "追加", id: 'button1', class: 'create_button'  }/
          %input{name: "button", type: "button", value: "削除", id: 'button2', class: 'create_button' }/
    %br
    = f.submit "登録", class: 'create_button' 
      

app/views/shared/_header.html.haml
.header
  .header__title
    = link_to'WHO?', root_path
  - if user_signed_in?
    .header__user
      .header__user--name
        = "#{current_user.nickname}でログイン中"
      .header__user--logout
        = link_to 'ログアウト', destroy_user_session_path, method: :delete

app/views/shared/_person.html.haml
.person-data
  = icon('fas', 'user-alt', class: 'icon')
  = person.name
  -# = link_to edit_person_path(person.id) do 
  -#   = icon('fas', 'cog',class: 'strong')
  %br
  年齢:
  = person.age
  性別:
  = person.gender
  体型:
  = person.body
  %br/
  身長:
  = person.height
  髪型:
  = person.hair
  %br/
  特徴:
  - person.characters.each do |character|
    = character.chara