config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root 'users#index'
  resources :users, only: :new

  resources :persons
  get 'people', to: 'persons#people'
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :characters, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :characters
  validates :name, :age, :gender, :height, :body, :hair, presence: true
  enum genders: {
    男性:1, 女性:2, その他:3
  }
  enum ages: {
   " ~20歳":1, "20~25歳":2, "25~30歳":3, "30~35歳":4, "35~40歳":5, "40~45歳":6, "45~50歳":7, "50~55歳":8, "55~60歳":9, "60歳~":10
  }
  enum heights: {
    "180cm~":1, "175~180cm":2, "170~175cm":3, "165~170cm":4, "160~165cm":5, "155~160cm":6, "~155cm":7
  }
  enum bodys: {
    筋肉質:1, 細身:2, 普通:3, ふくよか:4
  }
  enum hairs: {
    坊主:1, ベリーショート:2, ショート:3, セミロング:4, ロング:5, パーマ:6
  }
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_action :authenticate_user!

  def index
    # params[:q]["user_id_eq"] = current_user.id
    @q = current_user.persons.ransack(params[:q])
    @person = @q.result(distinct: true).page(params[:page])
  end

  def people
    @q = current_user.persons.ransack(params[:q])
    @person = @q.result(distinct: true).page(params[:page]).per(3)
  end

  def new
    @person = Person.new
    @person.characters.build
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to root_path
    else
      render :new
    end
  
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    person = Person.find(params[:id])
    person.update(person_params)
    redirect_to root_path
  end

  
  
  private

  def person_params
    params.require(:person).permit(:name, :gender, :age, :body, :height, :hair, characters_attributes: [:chara]).merge(user_id: current_user.id)
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/edit.html.haml
= render partial: "shared/header"
.new_people
  = render partial: "shared/form"

app/views/persons/index.html.haml
= render partial: "shared/header"

.person_index
  .person_index__search
    %h3 マイリスト 検索
    = search_form_for(@q, url: people_path) do |f| 
      = f.label :name, "ニックネーム・本名" 
      = f.search_field :name_cont 
      %br
      = f.label :gender, "性別"
      = f.select :gender_eq, Person.genders.keys, {prompt: '---'}
      = f.label :age, "年齢"
      = f.select :age_eq, Person.ages.keys, {prompt: '---'}
      = f.label :body, "体型"
      = f.select :body_eq, Person.bodys.keys, {prompt: '---'}
      %br/
      = f.label :height, "身長"
      = f.select :height_eq, Person.heights.keys, {prompt: '---'}
      = f.label :hair, "髪型"
      = f.select :hair_eq, Person.hairs.keys, {prompt: '---'}
      %br
      = f.label :chara, "特徴"
      = f.search_field :characters_chara_start, placeholder: "職業 話した内容など自由に・・・。"
      %br/
      %input{name: "button", type: "button", value: "リセット", id: 'button3', class:"search_button" }/
      = f.submit "検索" , class:"search_button"


  -# .contener
  -#   = render partial: "shared/person", collection: @person
  -#   = paginate(@person)

  
      

app/views/persons/new.html.haml
= render partial: "shared/header"
.new_people
  = render partial: "shared/form"
  -# .new_people__create
  -#   %l1 リスト登録
  -#   = form_for @person, url: persons_path, html: {class: "people_new"} do |f|
  -#     = render 'layouts/error_messages', model: f.object
  -#     = f.label :name, "本名　又は　ニックネーム"
  -#     = f.text_field :name
  -#     %br
  -#     = f.label :gender, "性別"
  -#     = f.select :gender, Person.genders.keys, {prompt: '---'}
  -#     = f.label :age, "年齢"
  -#     = f.select :age, Person.ages.keys, {prompt: '---'}
  -#     = f.label :body, "体型"
  -#     = f.select :body, Person.bodys.keys, {prompt: '---'}
  -#     %br/
  -#     = f.label :height, "身長"
  -#     = f.select :height, Person.heights.keys, {prompt: '---'}
  -#     = f.label :hair, "髪型"
  -#     = f.select :hair, Person.hairs.keys, {prompt: '---'}
  -#     %br
  -#     #chara-box
  -#       = f.fields_for :characters do |c|
  -#         .js-file_group{"data-index" => "#{c.index}"}
  -#           = c.label :chara, "特徴", class: 'js-file'
  -#           = c.text_field :chara, class: 'js-file'
  -#           %input{name: "button", type: "button", value: "追加", id: 'button1', class: 'create_button'  }/
  -#           %input{name: "button", type: "button", value: "削除", id: 'button2', class: 'create_button' }/
  -#     %br
  -#     = f.submit "登録", class: 'create_button' 
        

    

app/views/persons/people.html.haml
= render partial: "shared/header"

.contener
  .person_box
    = render partial: "shared/person", collection: @person
    = paginate(@person)